server:
  port: 8075
spring:
  application:
    name: sms-service
  rabbitmq:
    host: ly-mq
    username: leyou
    password: 123321
    virtual-host: /leyou
ly:
  sms:
    accessKeyID: LTAI5tDkq6259VrQCFot8EyP # 你自己的accessKeyId
    accessKeySecret: CzZdgYxXDb30f8NQILv9OERXOWYWxq # 你自己的AccessKeySecret
    signName: wl9939 # 签名名称
    verifyCodeTemplate: SMS_213302943 # 模板名称
    domain: dysmsapi.aliyuncs.com # 域名
    action: SendSMS # API类型，发送短信
    version: 2017-05-25 # API版本，固定值
    regionID: cn-hangzhou
logging:
  level:
    com.leyou: debug