server:
  port: 8086
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://192.168.58.154:3306/leyou?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  cloud:
    alibaba:
      seata:
        tx-service-group: order_tx_group
  redis:
    host: 192.168.58.154
  rabbitmq:
    host: 192.168.58.154
    username: leyou
    password: 123321
    virtual-host: /leyou
    template:
      retry:
        enabled: true       #开启生产者重试
        initial-interval: 10000ms     #重发的间隔
        max-interval: 80000ms     #重试的最大时间间隔
        multiplier: 2         #每次重试的时间倍数
    publisher-confirms: true    #是否开启生产者确认
eureka:
  client:
    service-url:
      defaultZone: http://192.168.58.76:10086/eureka
logging:
  level:
    com.leyou: debug
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      insert-strategy: not_null
      update-strategy: not_null
  type-aliases-package: com.leyou.user.entity
ly:
  encoder:
    crypt:
      secret: ${random.uuid} # 随机的密钥，使用uuid
      strength: 6 # 加密强度4~31，决定盐加密时的运算强度，超过10以后加密耗时会显著增加