server:
  port: 8081
spring:
  application:
    name: item-service
  cloud:
    alibaba:
      seata:
        tx-service-group: order_tx_group
  rabbitmq:
    host: ly-mq
    username: leyou
    password: 123321
    virtual-host: /leyou
    template:
      retry:
        enabled: true       #开启生产者重试
        initial-interval: 10000ms     #重发的间隔
        max-interval: 80000ms     #重试的最大时间间隔
        multiplier: 2         #每次重试的时间倍数
    publisher-confirms: true    #是否开启生产者确认
  #redis配置
  redis:
    # 主机配置，默认是localhost
    host: ly-redis
    # 密码，默认是没有密码
    password:
    # 第一个数据库，默认是0
    database: 0
    # 端口，默认是6379
    port: 6379
    #jedis连接池配置
    jedis:
      pool:
        max-active: 30
        min-idle: 5
        max-wait: 3000
    # 连接超时时间
    timeout: 3000
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://ly-mysql:3306/leyou?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://ly-registry:10086/eureka
mybatis-plus:
  type-aliases-package: com.leyou.item.entity # 别名扫描包
  # mapper-locations: classpath*: mappers/*.xml # mapper的xml文件地址
  global-config:
    db-config:
      id-type: auto # id默认为自增长
      update-strategy: NOT_EMPTY # 更新时，只更新非空字段
      insert-strategy: NOT_EMPTY # 新增时，只新增非空字段
logging:
  level:
    com.leyou: debug

ribbon:
  ConnectTimeout: 9000 # ribbon链接超时时长
  ReadTimeout: 9000 # ribbon读取超时时长

